# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'coderay'
gem 'rack-test'
gem 'rspec'
gem 'sequel'
gem 'sinatra'
gem 'sqlite3'
